casacore/python-casacore

casacore/fitting/__init__.py
casacore/fitting/fitting.py
casacore/functionals/__init__.py
casacore/functionals/functional.py
casacore/images/image.py
casacore/measures/__init__.py
casacore/tables/table.py
casacore/tables/wxtablebrowser.py
casacore/util/__init__.py

Mainly necessary for fixing imports on systems that do not
already have pyrap installed, which would be most systems
that install python-casacore because pyrap is now deprecated.

Replaced references to pyrap -> casacore

---

setup.py

This could be considered a quick-and-dirty fix. But I think it's a decent way do get pyrap working on OSX without rewriting the whole build system..

Link against boost_python-mt on OSX, fixes #15

---

casacore/fitting/__init__.py
casacore/fitting/fitting.py
casacore/functionals/__init__.py
casacore/functionals/functional.py
casacore/images/__init__.py
casacore/images/image.py
casacore/measures/__init__.py
casacore/quanta/__init__.py
casacore/quanta/quantity.py
casacore/tables/__init__.py
casacore/tables/table.py
casacore/tables/tablecolumn.py
casacore/tables/tableindex.py
casacore/tables/tableiter.py
casacore/tables/tablerow.py
casacore/tables/tableutil.py
casacore/util/__init__.py

To enable proper imports of sub modules, I use absolute imports pretty much everywhere. This should be able to run on Python versions 2.5 and higher.

Use absolute imports as much as possible to appease Python3

---

casacore/measures/__init__.py

It is a mappable that implements the __contains__ method. It does not
have a has_key() method. I therefore replaced all instances of os.environ.has_key(...)
with 'keyname' in os.environ.keys().

os.environ is not a dict: has no "has_key()" method

---

casacore/tables/table.py

For a bit more user friendliness, we could print the number of rows and all column names for table objects.

Make tables print their columns and the number of rows

---

README.rst

Docs are not automatically built yet, I can do that some other time. For now it is important that at least the current docs are online.

Move docs to casacore.github.io/python-casacore

---

setup.py

This should fix #25 in most cases, by adding the library files to the dependencies. Finding the full path is actually done by the compiler. I tried to mimic the search path, but can't guarantee that always works. If the libraries are not found, the dependency is not added and the old behavior is kept (so no error is thrown).

Add dependency on casacore libs

---

.travis.yml
casacore/quanta/__init__.py
doc/casacore_quanta.rst
src/quantamath.cc
test_requirements.txt
tests/test_fitting.py
tests/test_funcionals.py
tests/test_image.py
tests/test_measures.py
tests/test_quanta.py
tests/test_table.py
tests/test_util.py

fix for this PR
https://github.com/casacore/python-casacore/pull/39

Quanta: add dicts with all units and prefixes with Python 2.6 tests

---

casacore/tables/__init__.py
casacore/tables/msutil.py
casacore/tables/table.py
casacore/tables/tableutil.py
setup.py
src/pyms.cc
src/pytable.cc
src/tables.cc
src/tables.h
tests/test_table.py

Added three methods for creating canonical MeasurementSets and their subtables.
- `pyrap.tables.default_ms(name, tabdesc)`. This creates an MS called 'name' and associated subtables. Extra columns, hypercolumns and keywords can be specified in tabdesc which will overwrite/merge into the standard definition for the MS.
- `pyrap.tables.default_ms_subtable(subtable, tabdesc)`. This creates an MS subtable. For e.g. `default_ms_subtable("ANTENNA")` will created an ANTENNA subtable. Extra columns, hypercolumns and keywords can be specified in tabdesc which will overwrite/merge into the standard definition for the subtable.
- `pyrap.tables.msutils.required_ms_desc(table)`. Returns a dictionary table description for the specified table. `required_ms_desc("MAIN")` will return a description for a …

Add methods for creating a default MS

---

.gitignore
casacore/tables/__init__.py
casacore/util/substitute.py
tests/test_util.py

made doctests compatible and did minor changes to look code more pythonic

---

casacore/__init__.py
setup.py

Now that #72 is merged, python-casacore depends on casacore 2.3.0. We should check for this at setup time.

Check for minimum casacore version, fixes #79

---

casacore/images/image.py

The use of `-` was deprecated for some time. Apparently conda now installs a numpy which doesn't tolerate a `-` for negating an array anymore.

Replace deprecated - by numpy.logical_not

---

.travis.yml
.travis/before_install.sh

Python builds are not yet available on the OS X environment natively(https://github.com/travis-ci/travis-ci/issues/2312). Miniconda fixed the environment issue, but still python-casacore is having problem with data packages on osx environment on Travis.

Added osx-travis support

---

casacore/functionals/functional.py
casacore/images/coordinates.py
casacore/tables/__init__.py
casacore/tables/table.py
doc/199.html

* [In this page](http://casacore.github.io/python-casacore/casacore_functionals.html),  some of the examples are not related to the section(heading). Like in functionals.poly section, the example was given is of gaussian1d.I had tried to remove the duplicity. 
* Added some more points regarding creating a spectral coordinate and other coordinates.

improved docs.

---

casacore/measures/__init__.py

Remove some deprecated calls to `has_key` (removed in python 3.x), in favor of the pythonic `a in b` form. Thanks @jamiefarnes for spotting this in casacore/casacore#692

Remove deprecated has_key

---

src/pymeasures.h

The name of the macros used for guarding the header inclusion did not
correspond to each other, and therefore including the file multiple
times within a single compilation unit would have led to errors. I chose
the macro name without the _PY prefix because that aligns better with
what can be found in the rest of the headers under src/.

Correct header guard macro definition

---

setup.py

While compiling the python-casacore modules the compilation failed with:
```
[...]
line 199, in build_extension
_build_ext.build_extension(self, ext)
File "/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
target_lang=language)
File "/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
extra_preargs, extra_postargs, build_temp, target_lang)
File "/usr/lib/python3.6/distutils/unixccompiler.py", line 170, in link
libraries)
File "/usr/lib/python3.6/distutils/ccompiler.py", line 1105, in gen_lib_options
(lib_dir, lib_name) = os.path.split(lib)
File "/usr/lib/python3.6/posixpath.py", line 107, in split
p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This is because my casacore installation is in a …

Avoiding TypeError deep down in setuptool

---

casacore/tables/table.py

Using dict.iteritems did not work for Python3; replaced by six.iteritems(dict)

Use six.iteritems for Python3

---

setup.py

Force clang to use the C++11 standard (mandatory since casacore 3.0.0).
Look for the multithreaded version of Boost.Python first, which has a
different -mt extension on macOS. Linux does not use this extension, so
the extra checks should be safe on that platform. This avoids linking
to the non-mt version of the library (Homebrew installs both so it is
necessary to pick the right one).

Restore macOS support

---

setup.py
src/tables.cc

This change links TaQL's mscal and meas functions into the _tables module, so these functions can be used when a static library is built.

Make derivedmscal and meas functions known at start

---

casacore/images/image.py
tests/test_image.py

Accidently an incorrect operator was used to negate the mask in the image constructor.
It has been fixed. The documentation has been improved.

Use ~ instead of - to negate the mask

---

manylinux2010/wheel27.docker
manylinux2010/wheel34.docker
manylinux2010/wheel35.docker
manylinux2010/wheel36.docker
manylinux2010/wheel37.docker

Apparently this `mkdir` wasn't necessary since the script succeeded even with the typo. But let's fix the typo anyway.
[skip ci]

Fix typo in wheel scripts

---

casacore/tables/msutil.py
casacore/tables/table.py
casacore/tables/tableutil.py
doc/casacore_tables.rst
src/pyms.cc
tests/test_table.py

Required MS and subtable column + keywords definitions are exposed in `pyrap.tables.require_ms_desc`.
This PR exposes all optional column + keywords definitions in `pyrap.tables.complete_ms_desc`

Expose complete MS and subtable definitions

---

.travis.yml
.travis/py2-kern.docker
.travis/py3-kern.docker
.travis/py3_casacore_master.docker
casacore/__init__.py
setup.py

The travis tests using KERN all fail on a unicode error. Probably this was fixed in casacore 3.1.1, which has unicode improvements. I'll bump to KERN5 to see if it helps, but KERN5 has casacore ~2.5.0~ 3.0.0, so probably not.

Give error when casacore is too old

---

casacore/tables/table.py

Since the change to 64-bit row numbers, casacore returns an Int64 for nr of rows. Boost-python turns that into a long (e.g. 10L) in python. It appears that python's len function expects an int, so table.py changes the result into an int.

Fix of result of tablecolumn.len

---

manylinux2010/wheel27.docker
manylinux2010/wheel34.docker
manylinux2010/wheel35.docker
manylinux2010/wheel36.docker
manylinux2010/wheel37.docker
manylinux2010/wheel38.docker

Other data paths can still be used by putting this in ~/.casarc
measures.directory: /mypath/to/casacore/data
Fixes #181

Hardcode data path to that used in KERN / ubuntu

---

setup.py

There are two problems with having an install_requires dependency on the
external argparse package: first, the argparse module has been included
in the Python standard library since 2.7 and 3.2, and therefore there's
no need to install it externally; and secondly, the code in
python-casacore doesn't use this dependency. In fact the only place
where argparse is used is in setup.py itself, which is a testimony that
the module shipped with the standard library is enough.
Probably the `future` package is also not needed (it's used only to import `print_function` in one of the tests, but `print` can be used as a function already in 2.7), I can push a commit for that as well if required.

Remove dependency on external argparse package

---

setup.py
tests/test_convert.py

Like in 2f9ed55, this commit removes the dependency on the external
future package, which isn't needed by python-casacore in its current
state and intended target python versions.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>

Remove dependency on external future package

---

.github/workflows/extract-wheels.sh
.github/workflows/make_images.sh
CHANGELOG.md
casacore/__init__.py

The only fix is that the binary wheels have now been build with `-DPORTABLE=TRUE` so that Dysco works on all platforms.

Prepare for 3.5.2

---

.github/workflows/extract-wheels.sh
.github/workflows/make_images.sh
.github/workflows/py311_binary_wheel.docker

Added support for building docker images for Python 3.11. Dropped support for Python 3.6, which is EOL.

Add support for Python 3.11

---

casacore/measures/__init__.py

Otherwise the `\d` escape sequence doesn't make sense. This actually emits a warning in python 3.11.

Use raw string for RE pattern

---

setup.py

In the grand old days, Homebrew installed to `/usr/local` and all was well. Now, however, while Intel Homebrew still does this, Apple Silicon / M1 / M2 Homebrew has gone and picked a new prefix: `/opt/homebrew`. A good explanation of the rationale is at https://earthly.dev/blog/homebrew-on-m1/. Basically, Homebrew had to admit that Fink and MacPorts were right. 😛 
The solution is to call `brew --prefix` and add those libraries explicitly to the search list. Keep going if brew is not installed.
This addresses #252.

Explicitly add Homebrew libs to support Apple M1

---

setup.py

On linux systems, calling `brew` does not raise a CalledProcessError but a FileNotFoundError.

Fix brew not found error

---

MANIFEST.in
casacore/.aipsrc
casacore/__init__.py
setup.py

This PR ensures that the `casacore` data files (ephemerides and geodetic) are added to the generated source and binary distribution, and that they can be found at runtime.
To test the latter, you can use the following command, which should succeed:
```
python -c "from casacore.tables import taql; taql('calc meas.azel(\"Jupiter\",2016-06-28 19:54,\"DWL\") deg')"
```

Add casacore data files to package

---

CMakeLists.txt

On some systems, the wrong Boost.Python version is searched if the component name is not explicitly given as `python3`. This is now fixed.

Require Boost python3 component

---

casacore/fitting/fitting.py
casacore/functionals/functional.py
casacore/images/coordinates.py
casacore/images/image.py
casacore/measures/__init__.py
casacore/quanta/quantity.py
casacore/tables/msutil.py
casacore/tables/table.py
casacore/tables/tablehelper.py
casacore/tables/tableutil.py
casacore/tables/wxtablebrowser.py
casacore/util/substitute.py
pyproject.toml

Casacore (and the rest of the world) has effectively dropped support for python 2, I think we can drop this support here as well.

Remove dependency on six

---

.github/workflows/build_release.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
pyproject.toml

Fixed a bug in the `build_release.yml` workflow that caused only binary wheels to be uploaded to PyPI.
Also fixed a few other minor issues with the workflows `linux.yml` and `osx.yml`.

Fix bug in build_release workflow

---

.github/workflows/build_release.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
pyproject.toml

The current GitHub action that builds and publishes a release, fails to upload the source tar ball. The MR fixes the broken action. The probable cause of this was probably a half-baked upgrade to `v4` of the `upload` and `download` actions.

Fix GitHub action that uploads to PyPI
