casacore/tables/tablehelper.py

Issue #20 Added argument name to _check_index

---

casacore/images/image.py

This may be a bit lofar-specific but I'd like to at least propose this change.
I had some trouble doing a coordinate conversion because the code expected a fourth parameter. It was not directly clear to me that this was the polarisation axis (and that that axis is considered to change faster than the frequency). 
One thing I don't really know what to do with is that the polarisation axis is numbered (0-3) in pixel coordinates and (1-4) in world coordinates.

Proposal to edit documentation

---

casacore/tables/tableutil.py

tablecopy did not pass all arguments to t.copy
close #48

issue #48; pass all arguments to t.copy

---

tests/test_funcionals.py

There is an issue in ``set_masks`` because it does not change the masks, that's why I commented it out.
Also have to add tests for ``fdf`` and ``add`` functions, but I am not sure how they work.

Added gaussian1d tests

---

src/quantamath.cc

Some more brackets should fix this.

Fix getUnits, fixes #53

---

casacore/functionals/__init__.py

Fixed a typo error in doc

---

tests/test_funcionals.py

Added functionals.poly test

---

README.rst

Corrected indentation error to correctly render at PyPI

---

setup.py

Added library files path to setup.py. This removed compile warnings.

Added library file path for ubuntu 16.04

---

.coveragerc
.travis.yml

fixes issue #60 
This is the coveralls  output for my fork -> https://coveralls.io/github/shibasisp/python-casacore

Added coverage reporting using travis and coveralls

---

casacore/util/substitute.py
tests/test_util.py

The substitute function has been changed to perform the expected behaviour.
Close #87

Fixed substitute behaviour

---

casacore/functionals/functional.py
tests/test_functionals.py

Added gaussian2d test

---

casacore/functionals/__init__.py
casacore/functionals/functional.py
tests/test_functionals.py

I have commented out tests for `chebyshev` with complex datatypes as it was giving an error.
```
RuntimeError: RecordRep::get_pointer - incorrect data type used for field interval.
```

Added tests for casacore.functionals

---

tests/test_fitting.py

#109 should be merged before this PR to make travis pass.

Added tests for fitting

---

.dockerignore
.travis.yml
.travis/Dockerfile
.travis/before_install.sh
.travis/install.sh
.travis/script.sh
tests/requirements.txt

Don't merge before travis passes.

trying to fix travis again

---

setup.py

More robust and newbie friendly.

Improve the setup procedure

---

.travis/Dockerfile

hopefully, this solves the crash inside the container.
running the container on my machine locally doesn't crash.

update to KERN-4

---

.travis.yml
.travis/py2_casacore_master.docker
.travis/py3_casacore_master.docker

based on https://quay.io/repository/casacore/casacore

Also test against casacore master

---

CHANGELOG.md
casacore/__init__.py

prepare for 3.1.0

---

.travis.yml
.travis/mypy.docker
.travis/pep8.docker
.travis/py2_casacore_v3.1.docker
.travis/py3_casacore_v3.1.docker

based on the new quay.io/casacore/casacore docker images.

also test for 3.1 branch

---

casacore/measures/__init__.py
tests/test_measures.py

Fix python3 issue in measures get_value

---

setup.py

Add /usr/lib64

---

setup.py

The library dirs and include dirs found in setup.py are now passed
to the compiler. Find_boost has been improved to always prefer
library names with versions over those without. So 'boost_python36'
is now preferred over 'boost_python-mt' (it was the other way around).
Including the header dir will fix issues with 'missing symbols' since
it could happen that a header from a previous boost installation was
available in a system path, which was slightly incompatible with the
boost library used at runtime.

Improve find_boost and find_casacore in setup

---

MANIFEST.in

Include LICENSE in manifest

---

CHANGELOG.md
casacore/__init__.py
manylinux2010/wheel27.docker
manylinux2010/wheel34.docker
manylinux2010/wheel35.docker
manylinux2010/wheel36.docker
manylinux2010/wheel37.docker

Note that the changelog assumes that #194 and #195 will be merged before the release.

Prepare 3.3.0

---

setup.py

Warn about broken casacore 3.0.0 version number

---

README.rst
casacore/fitting/fitting.py
casacore/images/coordinates.py
casacore/images/image.py
casacore/measures/__init__.py
casacore/tables/msutil.py
casacore/tables/table.py
casacore/tables/tableutil.py
casacore/tables/wxtablebrowser.py

A little cleanup now so there's less left to clean later.
Greetings

replace six.print_() by print() available since Python2.6
